### ISSUE TITLE
Cannot create portage snapshot in docker

### ISSUE THREAD

**Issue by oxr463** [oxr463/gentoo-dotfiles#2]
```
/bin/sh .gentoo/bin/catalyst_setup.sh
06 Nov 2021 13:19:14 -00: NOTICE  : Loading configuration file: /etc/catalyst/catalyst.conf
06 Nov 2021 13:19:14 -00: NOTICE  : conf_values[options] = {'bindist', 'pkgcache', 'kerncache', 'seedcache', 'autoresume', 'snapcache'}
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/catalyst", line 37, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/catalyst/main.py", line 285, in main
    return _main(parser, opts)
  File "/usr/lib/python3.9/site-packages/catalyst/main.py", line 446, in _main
    namespaces.simple_unshare(
  File "/usr/lib/python3.9/site-packages/snakeoil/process/namespaces.py", line 288, in simple_unshare
    unshare(CLONE_NEWNS)
  File "/usr/lib/python3.9/site-packages/snakeoil/process/namespaces.py", line 68, in unshare
    raise OSError(e, os.strerror(e))
PermissionError: [Errno 1] Operation not permitted
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  195M  100  195M    0     0  29.2M      0  0:00:06  0:00:06 --:--:-- 32.5M
```

**Comment by oxr463** [comment]
Looks like it's catalyst in general, not just creating snapshots, (See: https://github.com/oxr463/gentoo-dotfiles/issues/3)
