### ISSUE TITLE
Catalyst snapshot not found

### ISSUE THREAD

**Issue by oxr463** [oxr463/gentoo-dotfiles#4]
```
catalyst -f stage1-openrc.spec 06 Nov 2021 14:24:34 -00: NOTICE  : Loading configuration file: /etc/catalyst/catalyst.conf                                                                       06 Nov 2021 14:24:34 -00: NOTICE  : conf_values[options] = {'pkgcache', 'kerncache', 'bindist', 'snapcache', 'autoresume', 'seedcache'}
06 Nov 2021 14:24:34 -00: NOTICE  : Processing spec file: stage1-openrc.spec
06 Nov 2021 14:24:34 -00: NOTICE  : Using target: stage1                         06 Nov 2021 14:24:34 -00: NOTICE  : Source file specification matching setting is: strict                                                                         06 Nov 2021 14:24:34 -00: NOTICE  : Accepted source file extensions search order: ['tar.xz', 'tpxz', 'xz', 'tar.bz2', 'bz2', 'tbz2', 'squashfs', 'sfs', 'tar.gz', 'gz', 'tar']                                                                     06 Nov 2021 14:24:34 -00: ERROR   : CatalystError: File Not Found: /var/tmp/catalyst/snapshots/gentoo-@TIMESTAMP@

ls /var/tmp/catalyst/snapshots/
gentoo-latest.tar.xz
```

Reference(s):
- https://wiki.gentoo.org/wiki/Catalyst#Inside_a_stage1.spec_file

**Comment by oxr463** [comment]
```diff
git diff stage1.spec stage1.spec.new
diff --git a/stage1.spec b/stage1.spec.new
index 973c92c..90549c6 100644
--- a/stage1.spec
+++ b/stage1.spec.new
@@ -1,11 +1,12 @@
 subarch: amd64
 target: stage1
-version_stamp: @TIMESTAMP@
+version_stamp: 2021.04.17
 rel_type: default
 profile: default/linux/amd64/17.1
-snapshot: @TIMESTAMP@
+snapshot: 2021.04.17
 source_subpath: default/stage3-amd64-latest
+compression_mode: pixz_x
 update_seed: yes
-update_seed_command: --update --deep @world
-portage_confdir: @REPO_DIR@/releases/portage/stages
-portage_prefix: releng
+update_seed_command: --update --deep --newuse @world
+#portage_confdir: @REPO_DIR@/releases/portage/stages
+#portage_prefix: releng
```

**Comment by oxr463** [comment]
```
catalyst -f stage1.spec                          06 Nov 2021 15:07:18 -00: NOTICE  : Loading configuration file: /etc/catalyst/catalyst.conf                                                                       06 Nov 2021 15:07:18 -00: NOTICE  : conf_values[options] = {'seedcache', 'snapcache', 'pkgcache', 'kerncache', 'autoresume', 'bindist'}
06 Nov 2021 15:07:18 -00: NOTICE  : Processing spec file: stage1.spec
06 Nov 2021 15:07:18 -00: NOTICE  : Using target: stage1                         06 Nov 2021 15:07:18 -00: NOTICE  : Source file specification matching setting is: strict                                                                         06 Nov 2021 15:07:18 -00: NOTICE  : Accepted source file extensions search order: ['tar.xz', 'tpxz', 'xz', 'tar.bz2', 'bz2', 'tbz2', 'squashfs', 'sfs', 'tar.gz', 'gz', 'tar']                                                                     06 Nov 2021 15:07:19 -00: ERROR   : CatalystError: File Not Found: /var/tmp/catalyst/builds/default/stage3-amd64-openrc-latest
```

**Comment by oxr463** [comment]
```
catalyst -f stage1.spec
06 Nov 2021 15:43:57 -00: NOTICE  : Loading configuration file: /etc/catalyst/catalyst.conf
06 Nov 2021 15:43:57 -00: NOTICE  : conf_values[options] = {'snapcache', 'bindist', 'kerncache', 'seedcache', 'autoresume', 'pkgcache'}
06 Nov 2021 15:43:57 -00: NOTICE  : Processing spec file: stage1.spec
06 Nov 2021 15:43:57 -00: NOTICE  : Using target: stage1                         06 Nov 2021 15:43:58 -00: NOTICE  : Source file specification matching setting is: strict                                                                         06 Nov 2021 15:43:58 -00: NOTICE  : Accepted source file extensions search order: ['tar.xz', 'tpxz', 'xz', 'tar.bz2', 'bz2', 'tbz2', 'squashfs', 'sfs', 'tar.gz', 'gz', 'tar']
06 Nov 2021 15:43:58 -00: NOTICE  : Source path set to /var/tmp/catalyst/builds/default/stage3-amd64-openrc-latest
06 Nov 2021 15:43:58 -00: NOTICE  : stage1 stage path is /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/tmp/stage1root                                  06 Nov 2021 15:43:58 -00: NOTICE  : --- Running action sequence: unpack
06 Nov 2021 15:43:58 -00: NOTICE  : Referenced SEEDCACHE does not appear to be a directory, trying to untar...
06 Nov 2021 15:43:58 -00: NOTICE  : Resume: "seed source" unpack resume point is disabled                                                                         06 Nov 2021 15:43:58 -00: NOTICE  : Resume: Target chroot is invalid, cleaning up...                                                                              06 Nov 2021 15:43:58 -00: NOTICE  : Removing AutoResume Points ...
06 Nov 2021 15:43:58 -00: NOTICE  : Emptying directory: /var/tmp/catalyst/tmp/default/.autoresume-stage1-amd64-openrc-latest
06 Nov 2021 15:43:58 -00: NOTICE  : Clearing the chroot path ...
06 Nov 2021 15:43:58 -00: NOTICE  : Emptying directory: /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest
06 Nov 2021 15:43:58 -00: NOTICE  : Starting auto from /var/tmp/catalyst/builds/default/stage3-amd64-openrc-latest
06 Nov 2021 15:43:58 -00: NOTICE  : to /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest (this may take some time) ..
Decompression Error: No mode was passed in or automatically detected
06 Nov 2021 15:43:58 -00: ERROR   : 'None' extraction of /var/tmp/catalyst/builds/default/stage3-amd64-openrc-latest to /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest failed.
06 Nov 2021 15:43:58 -00: NOTICE  : --- Running action sequence: unpack_snapshot
06 Nov 2021 15:43:58 -00: NOTICE  : Unpacking portage tree (this can take a long time) ...
06 Nov 2021 15:44:02 -00: NOTICE  : --- Running action sequence: setup_confdir
06 Nov 2021 15:44:02 -00: NOTICE  : --- Running action sequence: portage_overlay
06 Nov 2021 15:44:02 -00: NOTICE  : --- Running action sequence: base_dirs
06 Nov 2021 15:44:02 -00: NOTICE  : --- Running action sequence: bind            06 Nov 2021 15:44:03 -00: NOTICE  : --- Running action sequence: chroot_setup    06 Nov 2021 15:44:03 -00: NOTICE  : Setting up chroot...
06 Nov 2021 15:44:03 -00: ERROR   : Exception running action sequence chroot_setup                                                                                Traceback (most recent call last):
  File "/usr/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: '/var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/etc/'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/catalyst/base/stagebase.py", line 1515, in run
    getattr(self, x)()
  File "/usr/lib/python3.9/site-packages/catalyst/base/stagebase.py", line 1063, in chroot_setup
    shutil.copy('/etc/resolv.conf', self.settings['chroot_path'] + '/etc/')        File "/usr/lib/python3.9/shutil.py", line 426, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)                            File "/usr/lib/python3.9/shutil.py", line 293, in copyfile
    raise FileNotFoundError(f'Directory does not exist: {dst}') from e
FileNotFoundError: Directory does not exist: /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/etc/
06 Nov 2021 15:44:03 -00: NOTICE  : Cleaning up... Running unbind()
06 Nov 2021 15:44:03 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/var/tmp/portage is not a mount point. Skipping
```

**Comment by oxr463** [comment]
```
mkdir -p /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/etc/portage                                                     

catalyst -f stage1.spec
06 Nov 2021 15:52:28 -00: NOTICE  : Loading configuration file: /etc/catalyst/catalyst.conf
06 Nov 2021 15:52:28 -00: NOTICE  : conf_values[options] = {'bindist', 'kerncache', 'autoresume', 'seedcache', 'pkgcache', 'snapcache'}
06 Nov 2021 15:52:28 -00: NOTICE  : Processing spec file: stage1.spec
06 Nov 2021 15:52:28 -00: NOTICE  : Using target: stage1
06 Nov 2021 15:52:28 -00: NOTICE  : Source file specification matching setting is: strict
06 Nov 2021 15:52:28 -00: NOTICE  : Accepted source file extensions search order: ['tar.xz', 'tpxz', 'xz', 'tar.bz2', 'bz2', 'tbz2', 'squashfs', 'sfs', 'tar.gz', 'gz', 'tar']                                                                     06 Nov 2021 15:52:29 -00: NOTICE  : Source path set to /var/tmp/catalyst/builds/default/stage3-amd64-openrc-latest
06 Nov 2021 15:52:29 -00: NOTICE  : stage1 stage path is /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/tmp/stage1root
06 Nov 2021 15:52:29 -00: NOTICE  : Resume point detected, skipping target path setup operation...
06 Nov 2021 15:52:29 -00: NOTICE  : --- Running action sequence: unpack          06 Nov 2021 15:52:29 -00: NOTICE  : Referenced SEEDCACHE does not appear to be a directory, trying to untar...
06 Nov 2021 15:52:29 -00: NOTICE  : Resume: "chroot" is valid...
06 Nov 2021 15:52:29 -00: NOTICE  : Resume: "seed source" hash matches chroot...
06 Nov 2021 15:52:29 -00: NOTICE  : Resume: Valid resume point detected, skipping seed unpack operation...
06 Nov 2021 15:52:29 -00: NOTICE  : --- Running action sequence: unpack_snapshot 06 Nov 2021 15:52:29 -00: NOTICE  : --- Running action sequence: setup_confdir   06 Nov 2021 15:52:29 -00: NOTICE  : --- Running action sequence: portage_overlay 06 Nov 2021 15:52:29 -00: NOTICE  : --- Running action sequence: base_dirs
06 Nov 2021 15:52:29 -00: NOTICE  : --- Running action sequence: bind
06 Nov 2021 15:52:29 -00: NOTICE  : --- Running action sequence: chroot_setup
06 Nov 2021 15:52:29 -00: NOTICE  : Setting up chroot...                         06 Nov 2021 15:52:29 -00: WARNING : Overriding certain env variables may cause catastrophic failure.
06 Nov 2021 15:52:29 -00: WARNING : If your build fails look here first as the possible problem.
06 Nov 2021 15:52:29 -00: WARNING : Catalyst assumes you know what you are doing when setting these variables.
06 Nov 2021 15:52:29 -00: WARNING : Catalyst Maintainers use VERY minimal envscripts, if used at all.
06 Nov 2021 15:52:29 -00: WARNING : You have been warned.
06 Nov 2021 15:52:29 -00: NOTICE  : Writing the stage make.conf to: /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/etc/portage/make.conf
06 Nov 2021 15:52:29 -00: NOTICE  : STICKY-CONFIG is enabled
06 Nov 2021 15:52:29 -00: NOTICE  : --- Running action sequence: setup_environment
06 Nov 2021 15:52:29 -00: NOTICE  : --- Running action sequence: run_local
copying make.conf to /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/tmp/stage1root/etc/portage
Copying stage1-chroot.sh to /tmp                                                 copying stage1-chroot.sh to /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/tmp
copying chroot-functions.sh to /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/tmp
Ensure the file has the executable bit set
Running stage1-chroot.sh in chroot:
    chroot /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest /tmp/stage1-chroot.sh
chroot: failed to run command './tmp/stage1-chroot.sh': No such file or directory
06 Nov 2021 15:52:29 -00: ERROR   : CatalystError: cmd(['/usr/share/catalyst/targets/stage1/stage1-controller.sh', 'run']) exited 1
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/var/tmp/portage is not a mount point. Skipping
06 Nov 2021 15:52:29 -00: ERROR   : CatalystError: Stage build aborting due to error.
06 Nov 2021 15:52:29 -00: ERROR   : Exception running action sequence run_local
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/catalyst/base/stagebase.py", line 1409, in run_local
    cmd([self.settings['controller_file'], 'run'],
  File "/usr/lib/python3.9/site-packages/catalyst/support.py", line 53, in cmd
    raise CatalystError('cmd(%r) exited %s' % (args, ret),
catalyst.support.CatalystError: cmd(['/usr/share/catalyst/targets/stage1/stage1-controller.sh', 'run']) exited 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/catalyst/base/stagebase.py", line 1515, in run
    getattr(self, x)()
  File "/usr/lib/python3.9/site-packages/catalyst/base/stagebase.py", line 1418, in run_local
    raise CatalystError("Stage build aborting due to error.",
catalyst.support.CatalystError: Stage build aborting due to error.
06 Nov 2021 15:52:29 -00: NOTICE  : Cleaning up... Running unbind()
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/tmp/kerncache is not a mount point. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/var/cache/binpkgs is not a mount point. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/tmp/stage1root/proc is not a mount point. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/run is not a mount point. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/dev/shm does not exist. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/dev/pts does not exist. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/var/tmp/portage is not a mount point. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/var/cache/distfiles is not a mount point. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/var/db/repos/gentoo is not a mount point. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/dev is not a mount point. Skipping
06 Nov 2021 15:52:29 -00: NOTICE  : /var/tmp/catalyst/tmp/default/stage1-amd64-openrc-latest/proc is not a mount point. Skipping
```
